export default {
	"pages": {
		"root": {
			"pageUrl": "root",
			"name": "root",
			"children": [
				"677c6de9e5d27700189acbbc",
				"677c6de9e5d27700189acbc0"
			],
			"id": "root"
		},
		"677c6de9e5d27700189acbbc": {
			"id": "677c6de9e5d27700189acbbc",
			"name": "404",
			"pageUrl": "404"
		},
		"677c6de9e5d27700189acbc0": {
			"id": "677c6de9e5d27700189acbc0",
			"name": "index",
			"pageUrl": "index",
			"seo": {
				"title": ""
			}
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"background": ""
		},
		"seo": {
			"title": "BluWave Digital Entertainment ",
			"og:image": "https://uploads.quarkly.io/677c6de9e5d27700189acb9e/images/Second%20Vista%20Holdings.jpg?v=2025-01-09T04:25:47.071Z",
			"og:title": "BluWave Digital Entertainment ",
			"favicon_32px": "https://uploads.quarkly.io/677c6de9e5d27700189acb9e/images/Emey87-Trainee-Magic.32.png?v=2025-01-09T04:21:22.159Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/6309b04d5e5c6e0021560652/images/hellstrom-favicon-271.png?v=2023-03-29T20:05:13.498Z",
			"background_win10": "#F2EFEA",
			"description": "The premier company in music entertainment. Parent company of XZ1 Recordings.",
			"og:description": "The premier company in music entertainment. Parent company of XZ1 Recordings.",
			"favicon_apple_152px": "https://uploads.quarkly.io/6309b04d5e5c6e0021560652/images/hellstrom-favicon-152.png?v=2023-03-29T20:05:05.735Z",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}